### ISSUE TITLE
Bookmark Recipe

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#1]
# Bookmark Recipe

## Value Proposition

**As a user**

**I want to** mark recipes as favorites,

**so that** I can quickly access and track the ones I am most interested in.

## Description

<img src="https://github.com/user-attachments/assets/5a50f435-f02b-4eb7-886b-c678801be541"  width="180">
<img src="https://github.com/user-attachments/assets/c561364b-c6a5-4102-bed5-f69a87ed460e"  width="180">
<img src="https://github.com/user-attachments/assets/cb4abc07-9439-4209-aa52-f5f0eb51b710"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

### Component guide:

<img src="https://github.com/user-attachments/assets/83da36db-a322-4ead-b35e-826ec547a50e"  width="180">

## Acceptance Criteria

- Each listed recipe includes a bookmark option.
- In the detail page there is also the option to toggle the bookmark.
- Clicking the bookmark button of an unbookmarked recipe adds it to the bookmarked list.
- Clicking the bookmark button of a bookmarked recipe removes it from the bookmarked list.
- The bookmarked recipes are displayed on a separate list accessible via a new page dedicated to bookmarked recipes.
- There is a clearly visible link on the homepage to navigate to the bookmarked recipes page.
- There is a clearly visible link on the bookmarked recipes page to navigate back to the homepage.
- Bookmarked recipes are visually highlighted by a distinct bookmark icon color to differentiate them from unbookmarked recipes.
- If there are no bookmarked recipes in the bookmarked list, a message is displayed to the user indicating that there are no bookmarks.

## Tasks

- [x] Create feature branch `feature/bookmark-recipe`
- [x] Create the component 'FavoriteButton'. Use design- and color guides for styling.
- [x] Create the component 'QuickLink'. Use design- and color guides for styling.
- [x] Render the 'FavoriteButton' in 'RecipePreview'
- [x] In pages folder create a new file 'favorites.js'
- [x] In 'favorites.js' render all 'RecipePreview' which are favorites

- [x] Render the 'FavoriteButton' in the details page
- [x] Make sure that the correct recipe id is used when calling the bookmark function

**Comment by MerleMak** [comment]
How will you handle the onClick on the bookmark button? :)
