### ISSUE TITLE
No Favorite Recipe Component

### ISSUE THREAD

**Issue by stekug** [stepris/recipe-manager-mealove#13]
## Value proposition
As a user
I want to see a visually pleasing page, when no recipe is in the favorite list.

## Description
<img src="https://github.com/user-attachments/assets/cb4abc07-9439-4209-aa52-f5f0eb51b710"  width="180">

### Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- [x] When no recipe is in the favorite list, a nice page explains, how to add recipes to the favorite list
## Tasks
- [x] Create a new Component called "NoFavorite"
- [x] use the design guide for color and the layout
- [x] import the heart as an svg
- [x] style the svg with SC
- [x] render the Component instead of the FavoriteList when no recipe is on the favorite list
