### ISSUE TITLE
Hover Effect on Fav Icon

### ISSUE THREAD

**Issue by stekug** [stepris/recipe-manager-mealove#14]
## Value proposition
As a user 
I want to see a hover effect when hovering over the favorite icon.

## Description
<img src="https://github.com/user-attachments/assets/ef615f0e-0371-4df1-8dcd-f1d15c3f47af"  width="180">

### Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- [x] The hover effect works on the recipe list, on the detail page and on the favorite page.
- [ ] good visible to the user, who is hovering the fav icon.

## Tasks
- [x] style the fav icon, use the image as an idea
- [ ] use the design guide
