### ISSUE TITLE
Clean Preview Thumbnails with Hover Effect

### ISSUE THREAD

**Issue by stekug** [stepris/recipe-manager-mealove#15]
## Value proposition
As a user,
I want to see a clean and readable preview of every recipe in the list component,
so that I can easily browse and select recipes that interest me.

## Description
<img src="https://github.com/user-attachments/assets/edc68790-3fb8-449e-a686-7c1be1854e00"  width="180">

## Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance Criteria
- [x] When the user navigates to the recipe list page, they are presented with a clean and well-styled preview of each recipe.
- [x] The recipe preview should include the following elements:
  - [x] Recipe image
  - [x] Recipe title
- [x] The layout and design of the recipe preview should be clear and readable, following the style shown in the provided picture. ("MÖHRENSALAT"-Example)
- [x] When the user hovers over a recipe preview, a hover effect should be applied, as demonstrated in the provided picture. (Or from the experimental idea)
- [x] The hover effect may include subtle animations such as scaling, shadow effects, or text color changes to enhance user interaction.
- [x] For now, every RecipePreview "Highlight" is green, we will change this in a later user story for every category

## Tasks
- [x] Design the recipe list component (RecipePreview) based on the provided image, ensuring clean and readable styling.
- [x] Implement the hover effect as shown in the provided image.
- [x] Test the component in different screen sizes to ensure responsiveness and readability.
- [x] Update any relevant CSS files or components to reflect the new design.
- [x] Add Color Variables to styles.js -> use Tailwind colors (middle value (5)) for the border around the Preview Component
- [x] Experimental: Maybe try to use something like a scale effect (transform) and decide which effect looks best (Scale, border, etc.)
