### ISSUE TITLE
Lift up useRouter from QuickLinks to _app.tsx

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#18]
## Value proposition
As a developer
I want to have the '$isActive' prop in _app.tsx
In order to provide all app sites with this prop

### Current situation:
  
<img src="https://github.com/user-attachments/assets/a67a5c3f-6fcc-49bd-9e10-7fa8a269f453"  width="180">

## Acceptance criteria
- [ ] The '$isActive' prop used in Quicklinks component needs to be lifted up to the _app.tsx
- [ ] The prop must be drilled down at least to index.tsx, favorites.tsx and the Quicklink component in order to provide the given styling.
- [ ] After that, the prop can be used on other sites / components e.g. in the NavigationList to provide the hover effect on the Navigation links.

## Tasks
- [ ] In _apptsx use the router hook the same way as it is in QuickLinks at the moment and give the '$isActive' prop to the Components.
- [ ] Await the prop in favorites.tsx and index.tsx and provide it in the rendering of the QuickLinks component.
- [ ] In types.tsx type the '$isActive' prop in 'AppBaseProps'
- [ ] Remove the router hook from the QuickLinks component
