### ISSUE TITLE
Add app information in the README.md

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#19]
## Value proposition
As a user
I want to I want to have general information about the meaLove app
In order to know what the app is used for and what features it has

## Description

Use the markdown for formatting the README

## Acceptance criteria
- [ ] The README provides general information about:
  - [ ] the app itself and its purpose
  - [ ] the group members who worked on it
  - [ ] the features that are already implemented
  - [ ] the used libraries and framework
  - [ ] the used design mockup
## Tasks
- [ ] Create a new branch feature/appInformation
- [ ] In this feature branch rewrite the README.md of the app repository
- [ ] Update the README.md when fundamental changes are made

**Comment by Roland-Hufnagel** [comment]
What does this mean?
`Rewrite the README.md in the main branch of the repo.`
I hope you don't want to push to main directly. If there is a ticket, use the feature branch workflow. Of cause you can omit quality assurance. 
Instead of frequently updating the information I recommend to work with this userstory the same as with other userstories: Make more precise tasks and when the time comes grap the ticket and implement it. 
One more idea: You may want to introduce the team members in the readme.
