### ISSUE TITLE
Create Recipe

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#2]
# Create Recipe

## Value Proposition

**As a user**

**I want to** create and store new recipes,

**so that** I can keep track of the dishes I want to cook.

### Design guide:

<img src="https://github.com/user-attachments/assets/d4013717-af07-4795-a986-e7244d4b21f9"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance Criteria

- A form for adding recipes is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labeled fields for:
  - Recipe title
  - Recipe description
  - Ingredients
  - Recipe Duration
  - Categories
  - Recipe preparation
- The following fields are mandatory:
  - Recipe title, ingredients, Recipe preparation.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new recipe is added to the top of the recipes list.

> 💡 Recipe tags are not included. Will be added in an other user story

## Tasks

- [x] Create feature branch `feature/create-recipe`
- [x] Create a component 'RecipeForm' which renders a form to submit a new recipe
- [x] Use the mockup as a reference for design and style
- [x] Implement localStorage and use the local recipe data as default value
- [x] Handle the submit event and save the submitted data to the localStorage

> 💡Ignore upload images from the mockup for now, since t is not yet possible to add images at this stage. For this reason, a placeholder image should be saved when creating a recipe.
