### ISSUE TITLE
Add Difficulty and Category to Detail Page

### ISSUE THREAD

**Issue by stekug** [stepris/recipe-manager-mealove#21]
## Value Proposition
As a user,  
I want to see the "Difficulty" and "Category" information on the recipe Detail Page  
in order to better understand the complexity and type of the recipe.

## Description
<img src="https://github.com/user-attachments/assets/9690115c-c295-487f-9b92-1b9be8b0bdf6"  width="180">
  
## Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance Criteria
- [x] The "Difficulty" field is displayed on the DetailPage, following the design in the provided image.
- [x] The "Category" field is displayed on the DetailPage, following the design in the provided image.

## Tasks
- [x] Add the "Difficulty" field to the DetailPage component. (The recipe object already contains the difficulty key)
- [ ] Add the "Category" field to the DetailPage component. (The recipe object already contains the category key)
- [x] Implement the layout and styling of these fields based on the provided image.
