### ISSUE TITLE
Back-Arrow on details page

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#23]
## Value proposition
As a user
I want to have a back-arrow on the details page
In order to to get a clearer design and navigate the app more easily

## Description

###Color guide:
<img src="https://github.com/user-attachments/assets/ba38b193-337d-4053-8580-14cc136f100c"  width="180">
  
### Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- [x] On the details page there should be a back-arrow shown instead of the 'Back to recipe list' link
- [x] The back-arrow redirects to the page where the user was before e.g. home / explore / create recipe

## Tasks
- [x] Create a new feature branch 'feature/back-arrow'
- [x] On page [id].tsx remove the styled link and replace it with the left-arrow svg
- [x] Make the the arrow with a button element that has an onClick
- [x] The onClick button uses the router hook with the push(back) method.
