### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#24]
## Value proposition
As a developer
I want to have one general button component
In order to re-use the button in different components

### Design guide:
<img src="https://github.com/user-attachments/assets/b95c8ea9-4b0b-48e7-a157-f18d7e37251d"  width="180">
  
### Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- [ ] The button component should only rendered through one 'Button' component
- [ ] The appearance of the button will be handled through a prop inside the button component

## Tasks
- [x] Create a new branch feature/button
- [x] Create a new component 'Button' 
- [x] The component should return a button element
- [x] It receives the following props: 'children', 'variant', 'type', 'onClickBehavior'
- [x] The button adapts its style according to the props it received
- [x] The button should be able to display the different final styles given in the design guide
- [x] Use a switch case for deciding how to render it
- [x] Use styled components for the different styles

**Comment by stekug** [comment]
This looks good! Great idea!
