### ISSUE TITLE
Update Recipe

### ISSUE THREAD

**Issue by stekug** [stepris/recipe-manager-mealove#3]
## Value proposition
As a user

I want to update the details of existing recipes,

so that they reflect the most accurate and relevant information.

### Design guide:

<img src="https://github.com/user-attachments/assets/9b654133-45f7-4f12-a240-a41830410f49"  width="180">
<img src="https://github.com/user-attachments/assets/7219e9c7-a879-4ab5-9e80-54b2a6726c79"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- Each recipe details page includes an easily accessible edit option.
- Clicking the edit option opens a new page with a form pre-filled with the recipe's existing details for modification.
- The form allows for edits to all recipe details, including:
  - Recipe title
  - Recipe image
  - Recipe description
  - Ingredients
  - Recipe Duration
  - Categories
  - Recipe tags
  - Instructions
- The following fields are mandatory to be filled:
  - Recipe name, ingredients, instructions.
- The form section includes options for both saving and canceling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is immediately redirected to the details page of the edited recipe, and the changes are saved and reflected.
## Tasks
- [x] Create feature branch `feature/update-recipe`
- [x] Create a new button component by integrating the multifunctional button from an earlier user story and render it in the details page
- [x] Adjust the `RecipeForm` component to be able to use it as a component prefilled with the data from the recipe id. Conditionally render different elements
- [x] Create a new page `/recipes/[id]/edit` as a dynamic route to display edit functionality to the user for a specific recipe
- [x] Write the event handler logic in `_app.tsx` to handle editing events.
- [x] Render the `RecipeForm` in the previously created `RecipeEditPage`. 
- [x] In the `RecipeEditPage` grab the id from the router and find the correct recipe to pass down to the `RecipeForm`. 
- [x] Pass the `onEditRecipe` handler from there also down to the `RecipeForm` component
- [x] Clicking the 'Update' button saves the changes in the recipe. Write the handler for it in `RecipeForm`.
- [x] Clicking the 'Cancel' button closes the form and redirects the user to the details page, write a handler function for that as well in `RecipeForm`.
- [x] Make sure the form gets correctly prepopulated with data from the recipe. And correctly update local storage in harmony with the intended usage of `RecipeForm`.

> 💡 It is not yet possible to edit images at this stage.

**Comment by MerleMak** [comment]
Your tasks are very similar to the acceptance criteria, 
Try and write mroe like a todo list for the tasks not conditions to be met :)
