### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#32]
## Value proposition
As a user
I want to upload images of my recipes
In order to visually showcase the dishes I've made within the app

## Description
- The image upload feature should allow users to upload a photo of their recipe directly from their device.
- The uploaded image will be stored and managed by the Cloudinary image hosting service.
- The image upload is available on the create recipe form as well as on the edit page.
- Users can see a preview of the image after uploading and before saving it to their recipe entry.
- The uploaded image will be displayed alongside the recipe details.

### Style guide:
<img src="https://github.com/user-attachments/assets/e5cc4290-b65c-4a19-a32c-fbf6aa04b73a"  width="180">

## Acceptance criteria
- [x] If no image is uploaded, a default placeholder image will be used.
- [x] When an image is successfully uploaded, it should be stored in Cloudinary with the URL saved in the database.
- [ ] If the upload fails, an information should be displayed with the message: "Image upload failed. Please try again."
- [x] The user should be able to remove or replace the uploaded image before saving the recipe.
- [x] The uploaded image should automatically be resized and optimized for web display by Cloudinary.
- [x] There should be a preview of the uploaded image on create/edit page.

## Tasks
- [x] Create a new branch 'feature/image-upload.
- [x] Make a Cloudinary account.
- [x] In general you can use the Web Capstone Docs as a guidline for implementation:
  https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary
- [x] Integrate Cloudinary's API into the app for image uploads.
- [x] Implement the front-end interface for selecting, uploading, and previewing images. (Use the style-guide)
- [x] Write the backend logic to handle the image URL returned by Cloudinary and save it to the database.
- [x] Make sure to handle error cases like failed uploads or wrong file types here!
- [x] Ensure that the image is resized and optimized using Cloudinary's transformations.
