### ISSUE TITLE
Prep time and cooking time -> hours and minutes are both displayed

### ISSUE THREAD

**Issue by stepris** [stepris/recipe-manager-mealove#33]
## Value proposition
`As a` user 
`I want to` see the preparation and cooking times clearly displayed in hours and minutes on the recipe detail page,
`In order to` easily understand the time it takes to prepare and cook a dish

## Description
<img src="https://github.com/user-attachments/assets/e1c4880f-3161-431b-9129-0911c147cf42" width="180">

The recipe detail page currently displays preparation and cooking times only in minutes. To enhance user experience and clarity, the times should be displayed in a more structured format that breaks down the duration into hours and minutes.

## Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
**Display Format:**
   - The preparation and cooking times should be converted from minutes into a format that displays hours and minutes.
   - Examples:
     - **Preparation Time:** `70 minutes` should be displayed as `1 hour 10 minutes`
     - **Cooking Time:** `125 minutes` should be displayed as `2 hours 5 minutes`
   - The time should be displayed prominently on the detail page

**Conditional Formatting:**
   - If the total time is less than 60 minutes, it should only display minutes like it is now.
   - Examples:
     - **Preparation Time:** `45 minutes`
     - **Cooking Time:** `30 minutes`

## Tasks
- [ ] Create a new branch called `feature/hours-and-minutes`
- [ ] Update the frontend code to convert and display times from minutes into hours and minutes. Edit the `RecipeDetails` component for this.
- [ ] Implement conditional logic to display only minutes if the time is less than 60 minutes
- [ ] Test the feature with various time inputs to ensure accurate and clear display.
