### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by stepris** [stepris/recipe-manager-mealove#34]
## Value proposition
`As a` user 
`I want to` securely log in to the mealLove application
`so that` I can access my personalized recipe recommendations, save my favorite recipes, and manage my account

## Description

<img src="https://github.com/user-attachments/assets/a73595c6-cd47-419b-8aff-96e94f8a0d2f" width="180">

## Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- [x] The user can Login with a google account via a button in the app header
- [x] When the user is not logged in he/she can not create new recipes
- [x] The user can only edit and delete the self created recipes
- [x] The users can see their own created recipes on the "myrecipes" page (there should be a link in the navigation)

## Tasks
- [x] Create a new breanch called `feature/user-login`
- [x] Add a basic [OAuth login](https://next-auth.js.org/configuration/providers/oauth) to the application using the library [NextAuth](https://next-auth.js.org/)
- [x] You can use the [Web Capstone Docs](https://web-capstone-docs.neuefische.de/additional-libraries/nextauth) as a guidance for the implementation
- [x] Choose google as OAuth provider for the use case
