### ISSUE TITLE
Delete Recipe

### ISSUE THREAD

**Issue by stepris** [stepris/recipe-manager-mealove#4]
# Delete Recipe

## Value Proposition

**As a user**

**I want to** be able to delete recipes that are no longer relevant,

**so that** I can maintain a clean and organized recipes list, ensuring it’s always up to date.

### Design guide:

<img src="https://github.com/user-attachments/assets/9b654133-45f7-4f12-a240-a41830410f49"  width="180">
<img src="https://github.com/user-attachments/assets/70cc51aa-3483-46bd-8120-b24a860e279c"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance Criteria

- Each recipe details view includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and canceling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the user is immediately redirected to the overview of all recipes, and the recipe is removed from the list.
- If all recipes are deleted, a message appears indicating that there are no recipes and refering to the top of the page to add a new one.

## Tasks

- [x] Create feature branch `feature/delete-recipe`
- [x] Create a new component 'DetailDeleteButton' that triggers a pop up asking for confirmation
- [x] Delete the recipe from localStorage, when the user confirms the pop up otherwise close the pop up
  - For handling the event implement an event handler function
  - Delete localStorage element related to recipe id
