### ISSUE TITLE
Delete Ingredient

### ISSUE THREAD

**Issue by stepris** [stepris/recipe-manager-mealove#40]
## Value proposition
`As a user`
`I want to` be able to delete ingredients while editing or creating recipes
`In order to` easily manage and correct the ingredients list

## Description
The application should allow users to delete individual ingredients from the ingredients list when they are editing an existing recipe or creating a new one. This feature ensures that users can maintain accuracy in their recipes, making it easier to update or correct ingredients as needed without having to start from scratch.

<img src="https://github.com/user-attachments/assets/cda5c775-e659-44c6-ad77-908285a12ac4"  width="180">

## Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance criteria
- [ ] Each ingredient in the list should have a visible delete button (e.g. a trash icon) next to it.
- [ ] When the delete button is clicked, the corresponding ingredient should be removed from the list immediately.
- [ ] The recipe creation or editing process should continue smoothly after an ingredient is deleted

## Tasks
- [ ] Create a feature branch called `feature/delete-ingredient`
- [ ] Choose an appropriate icon (trash icon) to represent the delete action
- [ ] Create a button behind each ingredient row to delete the according ingredient
- [ ] Create an `onClick` function on the button that triggers a handler function that deletes the specific ingredient
- [ ] Pass the `ingredient-id` to the handler function
- [ ] Filter the existing data from the recipe and create a new ingredients array
- [ ] Use the state setter to update the recipe

**Comment by gunnarmon** [comment]
sounds great!
