### ISSUE TITLE
Recipe List

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#5]
# Recipe List

## Value Proposition

**As a user**

**I want to** browse a list of recipes,

**so that** I get inspired for new dishes to prepare.

### Design guide:
<img src="https://github.com/user-attachments/assets/7d922c9f-9704-45b3-b7be-6d1abad58332" width="180">

### Color guide:
<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273" width="180">

## Acceptance Criteria

- The homepage displays a list of recipe cards.
- The recipes list is headlined with its purpose.
- Each recipe card includes:
  - Recipe title
  - Recipe preview image
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [x] Create feature branch `feature/recipe-list`
- [x] Inspect and adapt the example data in the [assets folder](./assets/recipes.json)
  - [x] Maybe create your own data example. Think about object structure!
  - [x] Add an `imageUrl` for each recipe, for example from [unsplash.com](unsplash.com)
- [x] Create global styling (use provided design mockup and color sheet):
       - color variables
       - padding variables 
       -  etc.
- [x] Create a component 'RecipePreview'. Use the design mockup. For colors use the color sheet (variables).
- [x] Create a component 'RecipeList'. in 'RecipeList' map over the recipe array using the 'RecipePreview' with according props to create list items for each recipe.
- [x] Render the 'RecipeList' component in pages/index.js
