### ISSUE TITLE
Filter Recipes

### ISSUE THREAD

**Issue by stepris** [stepris/recipe-manager-mealove#6]
# Filter Recipes

## Value Proposition

**As a user**

**I want to** filter recipes based on categories and tags,

**so that** I can quickly find recipes that match my preferences and needs.

### Design

<img src="https://github.com/user-attachments/assets/3e9d57fb-cde9-4e0f-b5c2-08fbf73a02ad"  width="180">
<img src="https://github.com/user-attachments/assets/9908ec76-96f3-4032-b044-89e8d4d9cf59"  width="180">
<img src="https://github.com/user-attachments/assets/75054c5a-8d16-450a-84d2-9de59cc180fd"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

## Acceptance Criteria

- The recipes list includes a section with filter options.
- Users can filter recipes by:
  - Categories like breakfast, lunch, dinner, dessert.
> 💡 Recipe tags are not included. Will be added in another user story
- When clicking on Open Categories, a Dropdown menu shows the categories
-  When clicking one Category, the Dropdown closes itself
- Applied filters are clearly displayed on the recipes list, allowing users to see which filters are currently active.
- Users can clear the filter with a single click, by clicking the same category again, returning the list to its unfiltered state.
- The recipes list updates in real-time as filters are applied or removed.
- If no recipes match the selected filter criteria, a message is displayed indicating that no recipes were found.
- The filter interface is intuitive and easy to use, ensuring that new users can easily understand how to apply and clear filters.

## Tasks

- [x] Create feature branch `feature/filter-recipes`
- [x] Render the 'MainCategories' component in the /pages/recipes/index.js as well as in the /pages/favorites/index.js
- [x] in "MainCategories" render for every category from the categoryJson one IconComponent with the corresponding image for each category
- [x] Create a function that handles selection and deselection of one category
- [x] When the user makes a selection, highlight the selected category (stick to design and color guides)
- [ ] Make sure when the user clicks on another category the selection switches to that one (only one category can be active at a time)
