### ISSUE TITLE
Recipe Details

### ISSUE THREAD

**Issue by stekug** [stepris/recipe-manager-mealove#7]
## Value Proposition

**As a user**

**I want to** access detailed information about each recipe,

**so that** I can effectively prepare the dish.

### Design guide:

<img src="https://github.com/user-attachments/assets/9b654133-45f7-4f12-a240-a41830410f49"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/b19c2723-ee3e-4d32-aa5c-807f64da0273"  width="180">

### Component guide:

<img src="https://github.com/user-attachments/assets/a8dcc827-bdfa-4e99-9194-54b9d8ba6b1b"  width="180">

## Acceptance Criteria

- Each recipe in the recipes list includes a link to a details page.
- Each details page contains:
  - Recipe title
  - Recipe image
  - Ingredients
  - Recipe Duration
  - Instructions

## Tasks

- [x] Create feature branch `feature/recipe-details`
- [x] Create the components marked with green arrows in the component guide to create a basic detail page
- [x] Use the mockup as a reference for design and style
- [x] In pages/recipes/ create '[id].js'. Use the useRouter hook to access the id query parameter from router.query
- [x] Work with local data for now

## Additional notes

Moved from acceptance criteria (will be added in another user story): 
  - Categories (not in the design mockup yet)
  - Recipe tags (not in the design mockup yet)
  - Recipe Description (not in the design mockup yet, will be discussed - character limit?)
