### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by gunnarmon** [stepris/recipe-manager-mealove#9]
## Value proposition

As a user
I want to have a navigation bar
In order to navigate through the app

### Design guide:

<img src="https://github.com/user-attachments/assets/0aaaf3ee-27cd-4ab5-b8de-36fc73135eac"  width="180">
<img src="https://github.com/user-attachments/assets/2626db91-1119-4044-bdda-d3e80c2d70cf"  width="180">

### Color guide:

<img src="https://github.com/user-attachments/assets/c464728c-2d31-4932-aa75-960aa0b4649e"  width="180">

### Component guide:

<img src="https://github.com/user-attachments/assets/a0419d26-13ac-4e5e-b160-5a2f8096aa97"  width="180">

## Acceptance criteria

- All pages display the navigation bar at the top of the screen
- It includes:
  - The title that displays the title of the app and links to the root page
  - A menu button that displays a menu with two links, one linking to the 'Explore' page and one linking to 'Favorites'

## Tasks

- [x] Use provided guides in the description section as reference for styling etc.
- [x] Create a component 'Navigation'
- [x] Create a component 'AppTitle' and render it in 'Navigation'
- [x] In 'AppTitle' render the app title and the link to the root index page
- [x] Create a component 'NavigationMenu'
- [x] Create a component 'NavigationList'. It renders links to the 'Explore' and 'Favorites' pages 
- [x] 'NavigationMenu' renders a button with an onClick function that toggle 'NavigationList'

- [x] Create a component 'Layout' which gets the props 'children'
- [x] 'Layout' renders 'Navigation' and <main>{children}</main>
- [x] In /pages/\_\_app.tsx render 'Layout' wrapped around 'GlobalStyle' and 'Component'
